site_name: Warriors API Documentation
docs_dir: docs
nav:
  - Home: index.md
  - API:
      - Warriors API: api/warriors.md
      - Professions API: api/professions.md
      - Skills API: api/skills.md
  - User:
      - Registration: user/registration.md
      - Authentication: user/authentication.md
      - Account Settings: user/account_settings.md
theme:
  name: material
